#!/usr/bin/env python
import json
from sys import argv
from sys import exit
from subprocess import check_output


def get_drive_by_name(drive_name):
	disks = get_description()
	for disk in disks['blockdevices']:
		for partition in disk['children']:
			if partition['label'] == drive_name:
				return partition['name']

def get_description():
	return json.loads(check_output('lsblk -pJf'.split(' ')))

def get_drives():
	disks = get_description()
	drives = []
	if 'blockdevices' in disks:
		for disk in disks['blockdevices']:
			for partition in disk['children']:
				if partition['label'] != None:
					drives.append(partition['label'])
	return drives

if __name__ == '__main__':
	if '--describe' in argv:
		print(get_description())
	if '--drive-names' in argv:
		for name in get_drives():
			print(name)
	if '--drive' in argv:
		print(get_drive_by_name(argv[len(argv)-1]))

