#!/bin/sh
. "${HOME}/.cache/wal/colors.sh"
fg=$color7
bg=$color2
DMENU="dmenu -nb $fg -nf $bg -sb $bg -sf $fg"
DRIVE="$(montautils --drive-names --mounted | $DMENU)"
if [ -z $DRIVE ]
then
	exit 0
fi
udisksctl unmount -b "$(montautils --drive $DRIVE)"
