#!/bin/sh
. "${HOME}/.cache/wal/colors.sh"
fg=$color7
bg=$color2
DMENU="dmenu -nb $fg -nf $bg -sb $bg -sf $fg"
DRIVE="$(monta-utils --drive-names | $DMENU)"
if [ -z $DRIVE ]
then
	exit 0
fi
udisksctl mount -b "$(monta-utils --drive $DRIVE)"
